In [6]:
import numpy as np

### Basic Array Creation

In [11]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [12]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [13]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Random Generation Function

In [21]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [23]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
arr = np.ones((3,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
arr = np.linspace(0,1,23)
arr

array([0.        , 0.04545455, 0.09090909, 0.13636364, 0.18181818,
       0.22727273, 0.27272727, 0.31818182, 0.36363636, 0.40909091,
       0.45454545, 0.5       , 0.54545455, 0.59090909, 0.63636364,
       0.68181818, 0.72727273, 0.77272727, 0.81818182, 0.86363636,
       0.90909091, 0.95454545, 1.        ])

#### Random generation function 

In [33]:
arr = np.random.rand(10)
arr

array([0.20110122, 0.61459892, 0.32513909, 0.89849606, 0.14706946,
       0.17971019, 0.9035069 , 0.81039151, 0.59322541, 0.79265895])

In [34]:
arr = np.random.randint(1,34,5)
arr

array([28,  8, 18,  4, 27], dtype=int32)

#### Array Attributes

In [43]:
arr = np.array([[1,3,4,5],[4,3,2,1]])
arr

array([[1, 3, 4, 5],
       [4, 3, 2, 1]])

In [44]:
arr.shape

(2, 4)

In [46]:
arr.dtype


dtype('int64')

In [47]:
arr.size

8

#### Array Methods

In [62]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [63]:
arr.min()

np.int64(1)

In [64]:
arr.max()

np.int64(10)

In [69]:
arr.sum()
np.sum(arr,axis=1)

array([15, 40])

####  Reshaping and Resizing

### Array generation function

### Random Generation function

### Array Attributes 

### Array Methods

### Reshaping and resizing