In [6]:
import numpy as np

# Numpy Arrays

### Basic Arrays Creation

In [11]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [12]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

In [13]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Random Generation Function

In [21]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [23]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
arr = np.ones((3,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
arr = np.linspace(0,1,23)
arr

array([0.        , 0.04545455, 0.09090909, 0.13636364, 0.18181818,
       0.22727273, 0.27272727, 0.31818182, 0.36363636, 0.40909091,
       0.45454545, 0.5       , 0.54545455, 0.59090909, 0.63636364,
       0.68181818, 0.72727273, 0.77272727, 0.81818182, 0.86363636,
       0.90909091, 0.95454545, 1.        ])

#### Random generation function 

In [33]:
arr = np.random.rand(10)
arr

array([0.20110122, 0.61459892, 0.32513909, 0.89849606, 0.14706946,
       0.17971019, 0.9035069 , 0.81039151, 0.59322541, 0.79265895])

In [34]:
arr = np.random.randint(1,34,5)
arr

array([28,  8, 18,  4, 27], dtype=int32)

#### Array Attributes

In [43]:
arr = np.array([[1,3,4,5],[4,3,2,1]])
arr

array([[1, 3, 4, 5],
       [4, 3, 2, 1]])

In [44]:
arr.shape

(2, 4)

In [46]:
arr.dtype


dtype('int64')

In [47]:
arr.size

8

#### Array Methods

In [62]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [63]:
arr.min()

np.int64(1)

In [64]:
arr.max()

np.int64(10)

In [69]:
arr.sum()
np.sum(arr,axis=1)

array([15, 40])

# Numpy Indexing

In [75]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [77]:
arr[1:5]

array([12, 13, 14, 15])

In [78]:
arr[2::4]

array([13, 17])

### Numpy Indexing and Slicing of Matrix

In [81]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [82]:
arr[0]

array([1, 2, 3, 4, 5])

In [89]:
slice = arr[2:6,0:5]
slice

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [91]:
slice =  arr[0:2, 3:]
slice

array([[ 4,  5],
       [ 9, 10]])

In [93]:
col = arr[:,4]
col

array([ 5, 10, 15, 20, 25, 30])

### Boolean Indexing 

# Array Operations

### Arithmetic Operations

In [100]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [101]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [105]:
a1 -a2 


array([0, 0, 0, 0, 0])

In [106]:
a1 * a2

array([ 36,  49,  64,  81, 100])

### Broadcastind 

In [109]:
l1 = [2,4,5,6,7]
arr = np.array(l1)

In [111]:
arr + 10

array([12, 14, 15, 16, 17])

### Deep and Shallow Copy

In [112]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [113]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [114]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### matrix operations 